### PR TITLE
Add More Valid Architectures

### PR DESCRIPTION
**Pull request by giantramen**
Add armv7s armv7 and arm64 so it will build for 32 bit
iPhones.

### CODE REVIEW

**Comment by arturgrigor** [comment]
@giantramen Adding `VALID_ARCHS` is not needed. You just need to select the proper Xcode destination and it will build for that architecture. Removing the `UIRequiredDeviceCapabilities` key from the Info.plist it's a good idea though.

As a side note: This project is using almost the same configuration as PromiseKit (https://github.com/mxcl/PromiseKit) especially regarding the build configuration and platforms support.

**Comment by giantramen** [comment]
I see that PromiseKit only has i386 and x86_64 for VALID_ARCHS, but according to the documentation that shouldn't work:
["Specifies the architectures for which the binary may be built. During the build, this list is intersected with the value of ARCHS build setting; the resulting list specifies the architectures the binary can run on. If the resulting architecture list is empty, the target generates no binary."](https://developer.apple.com/legacy/library/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW85)

Is there something I'm missing here or is the documentation just misleading?

**Comment by arturgrigor** [comment]
Here's the doc about `VALID_ARCHS` from Xcode:
>A space-separated list of architectures for which the target should actually be built. For each target, this is intersected with the list specified in `ARCHS`, and the resulting set is built. This allows individual targets to opt out of building for particular architectures. If the resulting set of architectures is empty, no executable will be produced.

It seems that `VALID_ARCHS` is used to filter out the architectures supported by a target. What they do not specify is what happens if the `VALID_ARCHS` setting is missing but I think it's clear what happens after looking at the results.

**Comment by giantramen** [comment]
Removed the Valid Architectures. I was confused because in the empty state Xcode shows i386 and x86_64, even though it will build for all architectures.

**Review by arturgrigor — APPROVED** [review]

**Comment by giantramen** [comment]
Any chance you can merge this in? Would like to point back at a real release.

**Comment by yannickl** [comment]
@giantramen Sorry for the very late, your last commits and I don't know why. I merge it now, thank you for your contribution!

**Pull request merged**
